apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-template-works
  title: Test Pull Request Template (Works)
  description: Create a Pull request
  tags:
    - recommended
spec:
  owner: peimanja
  type: service

  parameters:
    - title: Repository Info
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - name: Fetch Test Repo
      action: fetch:plain
      input:
        url: https://github.com/peejayca/backstage-test/tree/main/apps/test-app/
        targetPath: ./apps/test-app

    - name: List Workspace
      action: debug:log
      input:
        listWorkspace: true

    - name: Move a file
      action: fs:rename
      input:
        files:
          - from: ./apps/test-app/test-file.txt
            to: test-file.txt

    - name: List Workspace
      action: debug:log
      input:
        listWorkspace: true

    - id: create_pr
      name: Create PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "[Automated PR] delete ${{ parameters.name }} service"
        description: "This pull request was automatically generated by the Backstage scaffolder"
        branchName: backstage-delete-service-${{ parameters.name }}

  output:
    links:
      - title: Pull Request
        url: ${{ steps.create_pr.output.remoteUrl }}
        icon: github
